name: Coverity
on:
  push:
    branches: [ master ]
  workflow_dispatch:
 
jobs:
  Coverity:
 
    runs-on: self-hosted
 
    env:
      COV_URL: ${{ secrets.COV_URL }}
      COV_USER: ${{ secrets.COV_USER }}
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      COVERITY_PROJECT: NodeGoat
      COVBIN: C:\Users\JeffreyFeddon\Coverity\CA_2022.12\bin
      BLDCMD: --no-command
      CHECKERS: --webapp-security
 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
   
    - name: Coverity Full Scan
      run: |
        C:\Users\JeffreyFeddon\Coverity\CA_2022.12\bin\cov-build.exe --dir idir --fs-capture-search . $env:BLDCMD
        C:\Users\JeffreyFeddon\Coverity\CA_2022.12\bin\cov-analyze.exe --dir idir --ticker-mode none --all
        C:\Users\JeffreyFeddon\Coverity\CA_2022.12\bin\cov-commit-defects.exe --dir idir --ticker-mode none --url http://localhost:8080 --stream nodegoat --user admin --password coverity
